sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
env:
  matrix:
    - RAILS_VERSION='~> 4.2.0'
    - RAILS_VERSION='~> 5.0.0'
    - RAILS_VERSION='~> 5.1.0'
    - RAILS_VERSION='~> 5.2.x'
    - RAILS_VERSION='~> 6'
before_install: gem install bundler -v 1.14.6
